[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd frontend && npm ci']

[phases.build]
cmds = ['cd frontend && npx prisma generate', 'cd frontend && npm run build']

[start]
cmd = 'cd frontend && npx prisma migrate deploy && npm start'
